import { notification } from "antd";

export const openErrorNotification = (title, description) => {
  notification["error"]({
    message: title,
    description: description
  });
};

export const openSuccessNotification = (title, description) => {
  notification["success"]({
    message: title,
    description: description
  });
};

export const openInfoNotification = (title, description) => {
  notification["info"]({
    message: title,
    description: description
  });
};

export const openWarningNotification = (title, description) => {
  notification["warning"]({
    message: title,
    description: description
  });
};

export const offences = [
  "Advertising Prostitution",
  "Armed Robbery",
  "Arson",
  "Assault",
  "Attempted Murder",
  "Bomb Possess and/or use of",
  "Breach Domestic Violence Protection Order",
  "Common Assault",
  "Conspiracy to Murder",
  "Dangerous Operation of a Vehicle",
  "Disobey Move-on Direction",
  "Disqualified Driving",
  "Drink Driving",
  "Driving Causing Death",
  "Drug Offences",
  "Extortion",
  "Fare Evasion",
  "Found in Places Used for Purpose of Prostitution Offences",
  "Fraud",
  "Fraud by Cheque",
  "Fraud by Computer",
  "Fraud by Credit Card",
  "Gaming Racing & Betting Offences",
  "Good Order Offences",
  "Grievous Assault",
  "Handling Stolen Goods",
  "Have Interest in Premises Used for Prostitution Offences",
  "Homicide (Murder)",
  "Identity Fraud",
  "Interfere with Mechanism of Motor Vehicle",
  "Kidnapping & Abduction etc.",
  "Knowingly Participate in Provision Prostitution Offences",
  "Life Endangering Acts",
  "Liquor (excl. Drunkenness)",
  "Manslaughter (excl. by driving)",
  "Manslaughter Unlawful Striking Causing Death",
  "Miscellaneous Offences",
  "Offences Against Property",
  "Offences Against the Person",
  "Other Drug Offences",
  "Other Fraud",
  "Other Handling Stolen Goods",
  "Other Homicide",
  "Other Offences",
  "Other Offences Against the Person",
  "Other Property Damage",
  "Other Prostitution Offences",
  "Other Sexual Offences",
  "Other Stealing",
  "Other Theft (excl. Unlawful Entry)",
  "Permit Minor to be at a Place Used for Prostitution Offences",
  "Possess and/or use other weapons; restricted items",
  "Possess Drugs",
  "Possess etc. Tainted Property",
  "Possess Property Suspected Stolen",
  "Procuring Prostitution",
  "Produce Drugs",
  "Prostitution Offences",
  "Public Nuisance",
  "Public Soliciting",
  "Rape and Attempted Rape",
  "Receiving Stolen Property",
  "Resist Incite Hinder Obstruct Police",
  "Robbery",
  "Sell Supply Drugs",
  "Serious Assault",
  "Serious Assault (Other)",
  "Sexual Offences",
  "Shop Stealing",
  "Stalking",
  "Stealing from Dwellings",
  "Stock Related Offences",
  "Traffic and Related Offences",
  "Trafficking Drugs",
  "Trespassing and Vagrancy",
  "Unarmed Robbery",
  "Unlawful Entry",
  "Unlawful Entry With Intent - Dwelling",
  "Unlawful Entry With Intent - Other",
  "Unlawful Entry With Intent - Shop",
  "Unlawful Entry With Violence - Dwelling",
  "Unlawful Entry Without Violence - Dwelling",
  "Unlawful Possess Concealable Firearm",
  "Unlawful Possess Firearm - Other",
  "Unlawful Use of Motor Vehicle",
  "Vehicles (steal from/enter with intent)",
  "Weapons Act Offences",
  "Weapons Act Offences - Other"
];

export const areas = [
  "Aurukun Shire Council",
  "Balonne Shire Council",
  "Banana Shire Council",
  "Barcaldine Regional Council",
  "Barcoo Shire Council",
  "Blackall Tambo Regional Council",
  "Boulia Shire Council",
  "Brisbane City Council",
  "Bulloo Shire Council",
  "Bundaberg Regional Council",
  "Burdekin Shire Council",
  "Burke Shire Council",
  "Cairns Regional Council",
  "Carpentaria Shire Council",
  "Cassowary Coast Regional Council",
  "Central Highlands Regional Council",
  "Charters Towers Regional Council",
  "Cherbourg Shire Council",
  "Cloncurry Shire Council",
  "Cook Shire Council",
  "Croydon Shire Council",
  "Diamantina Shire Council",
  "Doomadgee Shire Council",
  "Douglas Shire Council",
  "Etheridge Shire Council",
  "Flinders Shire Council",
  "Fraser Coast Regional Council",
  "Gladstone Regional Council",
  "Gold Coast City Council",
  "Goondiwindi Regional Council",
  "Gympie Regional Council",
  "Hinchinbrook Shire Council",
  "Hope Vale Shire Council",
  "Ipswich City Council",
  "Isaac Regional Council",
  "Kowanyama Shire Council",
  "Livingstone Shire Council",
  "Lockhart River Shire Council",
  "Lockyer Valley Regional Council",
  "Logan City Council",
  "Longreach Regional Council",
  "Mackay Regional Council",
  "Mapoon Shire Council",
  "Maranoa Regional Council",
  "Mareeba Shire Council",
  "McKinlay Shire Council",
  "Moreton Bay Regional Council",
  "Mornington Shire Council",
  "Mount Isa City Council",
  "Murweh Shire Council",
  "Napranum Shire Council",
  "Noosa Shire Council",
  "North Burnett Regional Council",
  "Northern Peninsula Area Regional Council",
  "Palm Island Shire Council",
  "Paroo Shire Council",
  "Pormpuraaw Shire Council",
  "Quilpie Shire Council",
  "Redland City Council",
  "Richmond Shire Council",
  "Rockhampton Regional Council",
  "Scenic Rim Regional Council",
  "Somerset Regional Council",
  "South Burnett Regional Council",
  "Southern Downs Regional Council",
  "Sunshine Coast Regional Council",
  "Tablelands Regional Council",
  "Toowoomba Regional Council",
  "Torres Shire Council",
  "Torres Strait Island Regional Counci",
  "Townsville City Council",
  "Weipa Town Council",
  "Western Downs Regional Council",
  "Whitsunday Regional Council",
  "Winton Shire Council",
  "Woorabinda Shire Council",
  "Wujal Wujal Shire Council",
  "Yarrabah Shire Council"
];

export const years = [
  "2001",
  "2002",
  "2003",
  "2004",
  "2005",
  "2006",
  "2007",
  "2008",
  "2009",
  "2010",
  "2011",
  "2012",
  "2013",
  "2014",
  "2015",
  "2016",
  "2017",
  "2018",
  "2019"
];
